[2022-11-24 11:39:14,592] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:39:14,593] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:39:14,595] {logging_mixin.py:115} INFO - [2022-11-24 11:39:14,595] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:39:23,259] {logging_mixin.py:115} INFO - [2022-11-24 11:39:23,248] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:39:23,265] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:39:23,308] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 8.741 seconds
[2022-11-24 11:39:53,646] {processor.py:153} INFO - Started process (PID=109) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:39:53,649] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:39:53,663] {logging_mixin.py:115} INFO - [2022-11-24 11:39:53,663] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:39:58,432] {logging_mixin.py:115} INFO - [2022-11-24 11:39:58,428] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:39:58,437] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:39:58,453] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 4.812 seconds
[2022-11-24 11:40:29,369] {processor.py:153} INFO - Started process (PID=181) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:40:29,371] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:40:29,372] {logging_mixin.py:115} INFO - [2022-11-24 11:40:29,372] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:40:35,178] {logging_mixin.py:115} INFO - [2022-11-24 11:40:35,172] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:40:35,182] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:40:35,201] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.834 seconds
[2022-11-24 11:41:00,898] {processor.py:153} INFO - Started process (PID=243) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:41:00,911] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:41:00,918] {logging_mixin.py:115} INFO - [2022-11-24 11:41:00,918] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:41:08,628] {logging_mixin.py:115} INFO - [2022-11-24 11:41:08,623] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:41:08,644] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:41:08,675] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 7.781 seconds
[2022-11-24 11:41:39,635] {processor.py:153} INFO - Started process (PID=322) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:41:39,641] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:41:39,643] {logging_mixin.py:115} INFO - [2022-11-24 11:41:39,643] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:41:45,037] {logging_mixin.py:115} INFO - [2022-11-24 11:41:45,026] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:41:45,042] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:41:45,075] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.445 seconds
[2022-11-24 11:42:15,944] {processor.py:153} INFO - Started process (PID=409) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:42:15,947] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:42:15,950] {logging_mixin.py:115} INFO - [2022-11-24 11:42:15,950] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:42:20,130] {logging_mixin.py:115} INFO - [2022-11-24 11:42:20,122] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:42:20,133] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:42:20,162] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 4.222 seconds
[2022-11-24 11:42:50,587] {processor.py:153} INFO - Started process (PID=476) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:42:50,589] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:42:50,592] {logging_mixin.py:115} INFO - [2022-11-24 11:42:50,592] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:42:55,201] {logging_mixin.py:115} INFO - [2022-11-24 11:42:55,193] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:42:55,240] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:42:55,269] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 4.685 seconds
[2022-11-24 11:43:26,030] {processor.py:153} INFO - Started process (PID=541) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:43:26,046] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:43:26,049] {logging_mixin.py:115} INFO - [2022-11-24 11:43:26,049] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:43:29,335] {logging_mixin.py:115} INFO - [2022-11-24 11:43:29,332] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:43:29,338] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:43:29,356] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 3.333 seconds
[2022-11-24 11:43:59,909] {processor.py:153} INFO - Started process (PID=609) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:43:59,913] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:43:59,914] {logging_mixin.py:115} INFO - [2022-11-24 11:43:59,914] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:44:05,336] {logging_mixin.py:115} INFO - [2022-11-24 11:44:05,319] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:44:05,340] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:44:05,376] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.472 seconds
[2022-11-24 11:44:36,352] {processor.py:153} INFO - Started process (PID=683) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:44:36,359] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:44:36,362] {logging_mixin.py:115} INFO - [2022-11-24 11:44:36,362] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:44:40,037] {logging_mixin.py:115} INFO - [2022-11-24 11:44:40,035] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:44:40,051] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:44:40,070] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 3.739 seconds
[2022-11-24 11:45:10,149] {processor.py:153} INFO - Started process (PID=755) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:45:10,150] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:45:10,151] {logging_mixin.py:115} INFO - [2022-11-24 11:45:10,151] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:45:14,699] {logging_mixin.py:115} INFO - [2022-11-24 11:45:14,682] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:45:14,720] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:45:14,753] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 4.607 seconds
[2022-11-24 11:45:45,562] {processor.py:153} INFO - Started process (PID=819) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:45:45,564] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:45:45,565] {logging_mixin.py:115} INFO - [2022-11-24 11:45:45,565] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:45:48,146] {logging_mixin.py:115} INFO - [2022-11-24 11:45:48,141] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:45:48,148] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:45:48,181] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.625 seconds
[2022-11-24 11:46:19,274] {processor.py:153} INFO - Started process (PID=887) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:46:19,276] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:46:19,278] {logging_mixin.py:115} INFO - [2022-11-24 11:46:19,277] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:46:24,487] {logging_mixin.py:115} INFO - [2022-11-24 11:46:24,483] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:46:24,489] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:46:24,508] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.238 seconds
[2022-11-24 11:46:54,696] {processor.py:153} INFO - Started process (PID=950) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:46:54,698] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:46:54,699] {logging_mixin.py:115} INFO - [2022-11-24 11:46:54,699] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:46:57,001] {logging_mixin.py:115} INFO - [2022-11-24 11:46:56,998] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:46:57,003] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:46:57,018] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.324 seconds
[2022-11-24 11:47:27,261] {processor.py:153} INFO - Started process (PID=1020) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:47:27,262] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:47:27,263] {logging_mixin.py:115} INFO - [2022-11-24 11:47:27,263] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:47:32,598] {logging_mixin.py:115} INFO - [2022-11-24 11:47:32,573] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:47:32,602] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:47:32,632] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.374 seconds
[2022-11-24 11:48:03,569] {processor.py:153} INFO - Started process (PID=1107) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:48:03,573] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:48:03,576] {logging_mixin.py:115} INFO - [2022-11-24 11:48:03,576] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:48:05,821] {logging_mixin.py:115} INFO - [2022-11-24 11:48:05,818] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:48:05,824] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:48:05,840] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.281 seconds
[2022-11-24 11:48:35,970] {processor.py:153} INFO - Started process (PID=1173) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:48:35,973] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:48:35,975] {logging_mixin.py:115} INFO - [2022-11-24 11:48:35,975] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:48:41,428] {logging_mixin.py:115} INFO - [2022-11-24 11:48:41,423] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:48:41,430] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:48:41,452] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.487 seconds
[2022-11-24 11:49:12,172] {processor.py:153} INFO - Started process (PID=1248) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:49:12,174] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:49:12,187] {logging_mixin.py:115} INFO - [2022-11-24 11:49:12,187] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:49:14,283] {logging_mixin.py:115} INFO - [2022-11-24 11:49:14,280] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:49:14,284] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:49:14,303] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.133 seconds
[2022-11-24 11:49:44,649] {processor.py:153} INFO - Started process (PID=1312) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:49:44,652] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:49:44,654] {logging_mixin.py:115} INFO - [2022-11-24 11:49:44,654] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:49:51,992] {logging_mixin.py:115} INFO - [2022-11-24 11:49:51,979] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:49:52,009] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:49:52,038] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 7.391 seconds
[2022-11-24 11:50:22,896] {processor.py:153} INFO - Started process (PID=1382) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:50:22,899] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:50:22,900] {logging_mixin.py:115} INFO - [2022-11-24 11:50:22,900] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:50:25,307] {logging_mixin.py:115} INFO - [2022-11-24 11:50:25,296] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:50:25,312] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:50:25,348] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.457 seconds
[2022-11-24 11:50:55,904] {processor.py:153} INFO - Started process (PID=1452) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:50:55,906] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:50:55,907] {logging_mixin.py:115} INFO - [2022-11-24 11:50:55,907] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:51:03,150] {logging_mixin.py:115} INFO - [2022-11-24 11:51:03,144] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:51:03,154] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:51:03,169] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 7.268 seconds
[2022-11-24 11:51:34,055] {processor.py:153} INFO - Started process (PID=1529) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:51:34,058] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:51:34,066] {logging_mixin.py:115} INFO - [2022-11-24 11:51:34,066] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:51:35,977] {logging_mixin.py:115} INFO - [2022-11-24 11:51:35,970] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:51:35,979] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:51:35,995] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 1.945 seconds
[2022-11-24 11:52:06,410] {processor.py:153} INFO - Started process (PID=1590) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:52:06,412] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:52:06,414] {logging_mixin.py:115} INFO - [2022-11-24 11:52:06,413] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:52:11,694] {logging_mixin.py:115} INFO - [2022-11-24 11:52:11,687] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:52:11,703] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:52:11,729] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.322 seconds
[2022-11-24 11:52:42,127] {processor.py:153} INFO - Started process (PID=1661) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:52:42,140] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:52:42,141] {logging_mixin.py:115} INFO - [2022-11-24 11:52:42,141] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:52:45,874] {logging_mixin.py:115} INFO - [2022-11-24 11:52:45,871] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:52:45,875] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:52:45,891] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 3.767 seconds
[2022-11-24 11:53:16,446] {processor.py:153} INFO - Started process (PID=1726) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:53:16,449] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:53:16,452] {logging_mixin.py:115} INFO - [2022-11-24 11:53:16,451] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:53:25,818] {logging_mixin.py:115} INFO - [2022-11-24 11:53:25,815] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:53:25,819] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:53:25,833] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 9.392 seconds
[2022-11-24 11:53:56,195] {processor.py:153} INFO - Started process (PID=1818) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:53:56,197] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:53:56,198] {logging_mixin.py:115} INFO - [2022-11-24 11:53:56,198] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:53:58,145] {logging_mixin.py:115} INFO - [2022-11-24 11:53:58,142] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:53:58,148] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:53:58,163] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 1.970 seconds
[2022-11-24 11:54:28,347] {processor.py:153} INFO - Started process (PID=1881) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:54:28,350] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:54:28,352] {logging_mixin.py:115} INFO - [2022-11-24 11:54:28,352] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:54:37,394] {logging_mixin.py:115} INFO - [2022-11-24 11:54:37,389] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:54:37,397] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:54:37,419] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 9.076 seconds
[2022-11-24 11:55:08,222] {processor.py:153} INFO - Started process (PID=1964) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:55:08,224] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:55:08,225] {logging_mixin.py:115} INFO - [2022-11-24 11:55:08,225] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:55:10,473] {logging_mixin.py:115} INFO - [2022-11-24 11:55:10,465] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:55:10,478] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:55:10,508] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.289 seconds
[2022-11-24 11:55:54,212] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:55:54,216] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:55:54,219] {logging_mixin.py:115} INFO - [2022-11-24 11:55:54,218] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:56:00,610] {logging_mixin.py:115} INFO - [2022-11-24 11:56:00,602] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:56:00,626] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:56:00,737] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 6.531 seconds
[2022-11-24 11:56:31,849] {processor.py:153} INFO - Started process (PID=97) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:56:31,852] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:56:31,853] {logging_mixin.py:115} INFO - [2022-11-24 11:56:31,853] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:56:34,349] {logging_mixin.py:115} INFO - [2022-11-24 11:56:34,345] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:56:34,350] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:56:34,366] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.521 seconds
[2022-11-24 11:57:05,374] {processor.py:153} INFO - Started process (PID=163) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:57:05,377] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:57:05,378] {logging_mixin.py:115} INFO - [2022-11-24 11:57:05,378] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:57:10,986] {logging_mixin.py:115} INFO - [2022-11-24 11:57:10,977] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:57:10,989] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:57:11,023] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.653 seconds
[2022-11-24 11:57:41,349] {processor.py:153} INFO - Started process (PID=246) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:57:41,364] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:57:41,366] {logging_mixin.py:115} INFO - [2022-11-24 11:57:41,366] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:57:49,708] {logging_mixin.py:115} INFO - [2022-11-24 11:57:49,701] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:57:49,713] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:57:49,738] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 8.392 seconds
[2022-11-24 11:58:20,274] {processor.py:153} INFO - Started process (PID=342) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:58:20,277] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:58:20,278] {logging_mixin.py:115} INFO - [2022-11-24 11:58:20,278] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:58:22,464] {logging_mixin.py:115} INFO - [2022-11-24 11:58:22,462] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:58:22,465] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:58:22,480] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.210 seconds
[2022-11-24 11:58:52,948] {processor.py:153} INFO - Started process (PID=406) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:58:52,952] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:58:52,954] {logging_mixin.py:115} INFO - [2022-11-24 11:58:52,954] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:58:56,407] {logging_mixin.py:115} INFO - [2022-11-24 11:58:56,403] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:58:56,413] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:58:56,432] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 3.489 seconds
[2022-11-24 11:59:27,284] {processor.py:153} INFO - Started process (PID=473) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:59:27,286] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 11:59:27,287] {logging_mixin.py:115} INFO - [2022-11-24 11:59:27,287] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:59:31,985] {logging_mixin.py:115} INFO - [2022-11-24 11:59:31,975] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 11:59:32,001] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 11:59:32,033] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 4.753 seconds
[2022-11-24 12:00:02,487] {processor.py:153} INFO - Started process (PID=545) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:00:02,489] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 12:00:02,492] {logging_mixin.py:115} INFO - [2022-11-24 12:00:02,492] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:00:06,466] {logging_mixin.py:115} INFO - [2022-11-24 12:00:06,462] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 12:00:06,467] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:00:06,489] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 4.007 seconds
[2022-11-24 12:00:36,752] {processor.py:153} INFO - Started process (PID=611) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:00:36,775] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 12:00:36,777] {logging_mixin.py:115} INFO - [2022-11-24 12:00:36,777] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:00:42,617] {logging_mixin.py:115} INFO - [2022-11-24 12:00:42,609] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 12:00:42,620] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:00:42,649] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.905 seconds
[2022-11-24 12:01:13,032] {processor.py:153} INFO - Started process (PID=676) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:01:13,035] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 12:01:13,042] {logging_mixin.py:115} INFO - [2022-11-24 12:01:13,042] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:01:15,461] {logging_mixin.py:115} INFO - [2022-11-24 12:01:15,449] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 12:01:15,465] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:01:15,506] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 2.482 seconds
[2022-11-24 12:01:46,518] {processor.py:153} INFO - Started process (PID=742) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:01:46,540] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 12:01:46,542] {logging_mixin.py:115} INFO - [2022-11-24 12:01:46,542] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:01:51,952] {logging_mixin.py:115} INFO - [2022-11-24 12:01:51,948] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 12:01:51,954] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:01:51,971] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 5.461 seconds
[2022-11-24 12:02:22,170] {processor.py:153} INFO - Started process (PID=826) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:02:22,172] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 12:02:22,174] {logging_mixin.py:115} INFO - [2022-11-24 12:02:22,174] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:02:26,072] {logging_mixin.py:115} INFO - [2022-11-24 12:02:26,070] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 12:02:26,073] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:02:26,087] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 3.922 seconds
[2022-11-24 12:02:56,711] {processor.py:153} INFO - Started process (PID=907) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:02:56,720] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 12:02:56,721] {logging_mixin.py:115} INFO - [2022-11-24 12:02:56,721] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:03:01,414] {logging_mixin.py:115} INFO - [2022-11-24 12:03:01,408] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 12:03:01,419] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:03:01,451] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 4.743 seconds
[2022-11-24 12:03:32,145] {processor.py:153} INFO - Started process (PID=973) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:03:32,149] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 12:03:32,151] {logging_mixin.py:115} INFO - [2022-11-24 12:03:32,151] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:03:35,199] {logging_mixin.py:115} INFO - [2022-11-24 12:03:35,191] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 12:03:35,215] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:03:35,246] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 3.107 seconds
[2022-11-24 12:04:05,687] {processor.py:153} INFO - Started process (PID=1044) to work on /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:04:05,691] {processor.py:641} INFO - Processing file /opt/airflow/dags/shipments_ETL.py for tasks to queue
[2022-11-24 12:04:05,693] {logging_mixin.py:115} INFO - [2022-11-24 12:04:05,693] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:04:13,927] {logging_mixin.py:115} INFO - [2022-11-24 12:04:13,923] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/shipments_ETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shipments_ETL.py", line 29, in <module>
    conn = psycopg2.connect(host=ENDPOINT, port=PORT, database=DBNAME, user=USER, password=PASSWORD, sslrootcert="SSLCERTIFICATE")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
[2022-11-24 12:04:13,929] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/shipments_ETL.py
[2022-11-24 12:04:13,946] {processor.py:161} INFO - Processing /opt/airflow/dags/shipments_ETL.py took 8.268 seconds
